name: My First Workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Hello from First Action"
        - name: List files
          run: ls -la
        - name: Read files
          run: cat README.md
